version: '3.8'
services:
  workspace:
    image: ghcr.io/prulloac/base:bookworm
    container_name: anas-didi95-portal-dev
    working_dir: /workspaces/anas-didi95-portal
    environment:
      - SHELL=/bin/bash
    volumes:
      - ./:/workspaces/anas-didi95-portal
    tty: true
    stdin_open: true
