spring:
  application:
    name: uam
  datasource:
    url: jdbc:h2:mem:uamdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
