spring:
  application:
    name: uam
  datasource:
    username: "sa"
    password: "sa"
    url: "jdbc:h2:./h2/portal;AUTO_SERVER=TRUE"
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
