# Reference: https://docs.github.com/en/actions/tutorials/build-and-test-code/java-with-maven
# Reference: https://github.com/actions/starter-workflows/blob/main/ci/maven.yml
# Reference: https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml
# Reference: https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml

name: Spring Boot CI with Maven - UAM

on:
  workflow_dispatch:
  push:
    branches: ["main", "develop"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main", "develop"]

env:
  APP_NAME: uam
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}--uam
  JAVA_VERSION: 25
  JAVA_DIST: temurin

jobs:
  build-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DIST }}
      - name: Build with Maven Wrapper
        run: ./mvnw clean package -pl ${{ env.APP_NAME }} -am
      - name: Prepare artifact
        run: |
          mkdir artifact
          cp ${{ env.APP_NAME }}/target/*.jar artifact/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ env.APP_NAME }}
          path: app/artifact/
          retention-days: 1

  docker-publish:
    needs: [build-app]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Display structure of downloaded files
        run: ls -R
      - name: Stage artifact for Docker build
        run: |
          mkdir -p app/${{ env.APP_NAME }}/target
          ls -R
          cp app-${{ env.APP_NAME }}/*.jar app/${{ env.APP_NAME }}/target/
      - name: Install cosign
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: "v2.2.4"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: app/${{ env.APP_NAME }}
          file: app/${{ env.APP_NAME }}/Dockerfile.publish
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Retrieve OIDC token
        id: auth
        uses: actions/github-script@v7
        with:
          retries: 2
          script: |
            const token = process.env.ACTIONS_ID_TOKEN_REQUEST_TOKEN;
            const repoPath = process.env.GITHUB_REPOSITORY_OWNER + '/' + process.env.GITHUB_REPOSITORY;
            const res = await fetch(
              `${process.env.ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sigstore`
            );
            const data = await res.json();
            core.setOutput('oidc', data.value);
      - name: Sign the published Docker image
        if: github.event_name != 'pull_request'
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes --identity-token ${{ steps.auth.outputs.oidc }} {}@${DIGEST}
